name: 'workflows日志自动清理'

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  del_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: '3'
