name: 百度签到

on:
    workflow_dispatch:
    schedule:
        - cron: "30 04 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.actor == 'BlueSkyClouds'
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: npm install
              run: |
                  npm install
            - name: "运行【百度签到】"
              run: |
                  node function/tieba/tieba.js
              env:
                  BDUSS: ${{ secrets.BDUSS }}
                  JUMP: ${{ secrets.BDUSS_JUMP }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
                  TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
                  TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
#最后推送 2021年9月20日
